### ISSUE TITLE
挖掘后不统计？

### ISSUE THREAD

**Issue by MediatorYang** [crackun24/TheStarryMiningList#7]
（等更新好久了....）
装上之后挖掘方块不统计，然后后台报错，挖掘不产生掉落物

https://github.com/crackun24/TheStarryMiningList/assets/118263842/2ea0f993-422d-4004-bce2-02a077d48603

附上服务器日志
[latest.log](https://github.com/crackun24/TheStarryMiningList/files/14277195/latest.log)

**Comment by crackun24** [comment]
会尽快解决的

**Comment by crackun24** [comment]
已修复

**Comment by crackun24** [comment]
已解决
