### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by Xing688** [crackun24/TheStarryMiningList#9]
挖掘榜单和Masa Gadget的自动补货允许2x2合成（restockWithCrafting）有冲突会导致客户端崩溃，mod装在服务端

**Comment by crackun24** [comment]
提供一下服务器日志

**Comment by Xing688** [comment]
崩溃的是客户端，只有客户端的崩溃日志，稍后方便会上传



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月14日(周四) 上午6:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [crackun24/TheStarryMiningList] bug提交 (Issue #9)




 
提供一下服务器日志

**Comment by crackun24** [comment]
如果崩溃的是客户端而且本模组安装在服务端的话则崩溃与本模组大概率无关

**Comment by crackun24** [comment]
崩溃与本模组无关
